/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;


import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CursoListar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public CursoListar() { //construtor
        initComponents();// inicializa interface gráfica (Swing)
        listarCursos();// carrega os cursos do banco ao abrir a tela

        //Esconde a coluna ID da tabela (mas continua existindo internamente)
        jTable1.getColumn("ID").setMinWidth(0);
        jTable1.getColumn("ID").setMaxWidth(0);
        jTable1.getColumn("ID").setWidth(0);
        jTable1.getColumn("ID").setPreferredWidth(0);
    }

    private void listarCursos() {

        try {
            // pega o modelo da tabela (estrutura da JTable)
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

            modelo.setRowCount(0);  // limpa a tabela antes de recarregar os dados
            
            CursoIController cursoController = new CursoController();
             // cria acesso ao banco

            for (Curso curso : cursoController.findAll()) {// percorre todos os cursos do banco
                // adiciona cada curso como uma linha na tabela
                modelo.addRow(new Object[]{
                    curso.getId(),
                    curso.getNome(),
                    curso.getQuantidade(),
                    curso.getDescricao(),
                    curso.getFornecedor(),
                    "Excluir",// botão textual
                    "Editar"// botão textual
                });
            }

        } catch (Exception e) {  // mostra erro caso falhe ao carregar dados
            JOptionPane.showMessageDialog(this, "Erro ao listar: " + e.getMessage());
        }
    }

    public void recarregarTabela() {
        listarCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtBusca = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnHomes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "QUANTIDADE", "DESCRIÇÃO", "FORNECEDOR", "REMOVER", "EDITAR"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 740, 260));

        txtBusca.addActionListener(this::txtBuscaActionPerformed);
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });
        getContentPane().add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 262, -1));

        btnAdd.setText("+");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 38, -1, -1));

        btnHomes.setText("Homescreen");
        btnHomes.addActionListener(this::btnHomesActionPerformed);
        getContentPane().add(btnHomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 110, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomesActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        CursoCadastrar tela = new CursoCadastrar();     // abre tela de cadastro

        tela.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed
//filtra os cursos conforme você digita no campo de busca
    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        try {
            String busca = txtBusca.getText().toLowerCase();
            if (busca.isEmpty()) {
                listarCursos();
                return;
            }

            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);

            CursoIController cursoController = new CursoController();

            for (Curso curso : cursoController.findAll()) {
                if (curso.getNome().toLowerCase().contains(busca)) {
                    modelo.addRow(new Object[]{
                        curso.getId(),
                        curso.getNome(),
                        curso.getQuantidade(),
                        curso.getDescricao(),
                        curso.getFornecedor(),
                        "Excluir",
                        "Editar"
                    });
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro na busca: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_txtBuscaKeyReleased
// Método executado quando o usuário clica em alguma célula da tabela

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row = jTable1.getSelectedRow(); // Pega a linha selecionada
        int col = jTable1.getSelectedColumn();// Pega a coluna selecionada

        if (row == -1 || col == -1) {  // Se nenhuma linha ou coluna foi selecionada, encerra o método
            return;
        }

        CursoIController cursoController = new CursoController(); // Cria um objeto para acessar os métodos do banco

        // Pega o ID do curso da linha selecionada
        // O ID está armazenado na coluna 0 da tabela
        Long id = (Long) jTable1.getValueAt(row, 0);

        // Pega o valor da célula clicada
        Object valorObj = jTable1.getValueAt(row, col);

        // Converte o valor para String
        // Se for null, recebe string vazia
        String valor = (valorObj != null) ? valorObj.toString() : "";

        // Verifica se clicou na coluna "Excluir"
        // e se o texto da célula é "Excluir"
        if (col == 5 && "Excluir".equals(valor)) {

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Tem certeza que deseja excluir este curso?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {

                Curso curso = cursoController.findById(id);
                cursoController.delete(curso);

                listarCursos();
            }
        }

        if (col == 6 && "Editar".equals(valor)) {

            Curso cursoEncontrado = cursoController.findById(id);

            if (cursoEncontrado == null) {
                JOptionPane.showMessageDialog(this, "Curso não encontrado.");
                return;
            }

            CursoEditar tela = new CursoEditar(cursoEncontrado, this);
            tela.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHomes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
